---
title: "AlphaFold Analysis"
author: "Aileen Andrade (PID A17033749)"
format: pdf
---

Here we analyze our AlphaFold structure prediction models. The input directory/folder comes from the ColabFold server:

## 7.

```{r}
library("bio3d")
library(pheatmap)
alignment <- read.fasta("muscle-I20250304-204254-0769-79950964-p1m.fa") 
```

```{r}
identity_matrix <- seqidentity(alignment) 
```

```{r}
p <- pheatmap(identity_matrix)
```

## 8. Custom analysis of resulting models

```{r}
results_dir <- "test_a8676"
```

```{r}
pdb_files <-list.files(path=results_dir,
                       pattern="*.pdb",
                       full.names = TRUE)
basename(pdb_files)
```
```{r}
alignment$id
```

```{r}
library(bio3d)
```


```{r}
pdb_inputseq <- paste0(alignment$ali[7,], collapse ="") #Row 7 is the Haliotis_discus_RBP4_homolog (novel protein)

blast_pdb_res <- blast.pdb(pdb_inputseq)

hits <- blast_pdb_res$hit.tbl
```

```{r}
pdb_annot <- pdb.annotate(c("2HZQ_A", "7YX1_A", "1Z24_A"))

pdb_annot_res <- pdb_annot[,c(1,5,6,11)]

hits_stats <- hits[hits$subjectids %in% c("2HZQ_A", "7YX1_A", "1Z24_A"), c("identity", "evalue")]

q8_res <- cbind(pdb_annot_res, hits_stats)

q8_res <- q8_res[, c(3,1,2,4,5)]

write.csv(q8_res, "Q8_top3_res.csv", row.names = F)

```
